/**
 * Regenerate src/data/mapArt.ts from tarkov.dev's frontend config.
 *
 * The bounds/labels/rotation that place markers on map artwork are not part of
 * any API — they live in an application repo. We vendor them rather than fetch
 * at runtime so a rename upstream leaves us stale rather than broken.
 *
 * Run with:  npm run mapart
 */
import { writeFileSync } from 'node:fs'

const SOURCE = 'https://raw.githubusercontent.com/the-hideout/tarkov-dev/main/src/data/maps.json'
const OUT = new URL('../src/data/mapArt.ts', import.meta.url)

/** Only the maps that actually carry quest objective positions. */
const WANTED = [
  'customs',
  'factory',
  'ground-zero',
  'interchange',
  'lighthouse',
  'reserve',
  'shoreline',
  'streets-of-tarkov',
  'the-lab',
  'the-labyrinth',
  'woods',
]

interface UpstreamMap {
  key: string
  bounds?: [[number, number], [number, number]]
  coordinateRotation?: number
  svgPath?: string
  tilePath?: string
  labels?: { position: [number, number]; text: string }[]
}

const raw = await (await fetch(SOURCE)).json()
const groups = (Array.isArray(raw) ? raw : Object.values(raw)) as { maps: UpstreamMap[] }[]

const picked = new Map<string, UpstreamMap>()
for (const g of groups) for (const m of g.maps ?? []) if (WANTED.includes(m.key)) picked.set(m.key, m)

const missing = WANTED.filter((k) => !picked.has(k))
if (missing.length) throw new Error(`upstream config no longer has: ${missing.join(', ')}`)

const q = (s: string) => JSON.stringify(s)

const entries = [...picked.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([key, m]) => {
    if (!m.bounds) throw new Error(`${key} has no bounds`)
    const labels = (m.labels ?? [])
      .map((l) => `      { x: ${l.position[0]}, z: ${l.position[1]}, text: ${q(l.text)} },`)
      .join('\n')
    return [
      `  ${q(key)}: {`,
      `    bounds: [[${m.bounds[0][0]}, ${m.bounds[0][1]}], [${m.bounds[1][0]}, ${m.bounds[1][1]}]],`,
      `    rotation: ${m.coordinateRotation ?? 0},`,
      `    svg: ${m.svgPath ? q(m.svgPath) : 'null'},`,
      `    labels: [`,
      labels,
      `    ],`,
      `  },`,
    ]
      .filter((l) => l !== '')
      .join('\n')
  })

const header = `/**
 * Map artwork and world-space bounds, vendored from tarkov.dev's frontend.
 *
 * GENERATED by scripts/make-map-art.ts — run \`npm run mapart\` to refresh.
 * Source: the-hideout/tarkov-dev, src/data/maps.json.
 *
 * Vendored rather than fetched at runtime: it is a file in an application repo
 * with no versioning guarantee, so a rename upstream would silently empty the
 * map view. Stale beats broken.
 *
 * Coordinates are RAW GAME WORLD UNITS, which is what makes this usable.
 * Verified against the live API: the Customs "Old Gas" label sits at
 * (331, -173) and the Old Gas Station extract reports world (309, -174). So
 * objective positions plot straight against these bounds with no transform —
 * the "transform" array upstream is for aligning raster tile pyramids.
 *
 * "rotation" orients the artwork so north reads up. It is applied to the image
 * and the markers together, so it cannot misalign them; it only decides which
 * way the map faces on screen. It disagrees with the API's
 * coordinateToCardinalRotation on Reserve and The Labyrinth — this is the value
 * that matches this artwork.
 *
 * "svg" is null for maps published only as raster tile pyramids (The Lab, The
 * Labyrinth). Those render no background today.
 */
export interface MapLabel {
  x: number
  z: number
  text: string
}

export interface MapArt {
  /** [[maxX, minZ], [minX, maxZ]] in world units. */
  bounds: [[number, number], [number, number]]
  /** Degrees; applied to image and markers together. */
  rotation: number
  /** Null when the map has no SVG published. */
  svg: string | null
  labels: MapLabel[]
}

export const MAP_ART: Record<string, MapArt> = {
`

writeFileSync(OUT, `${header}${entries.join('\n')}\n}\n`)

console.log(
  JSON.stringify(
    {
      maps: picked.size,
      withSvg: [...picked.values()].filter((m) => m.svgPath).length,
      tilesOnly: [...picked.values()].filter((m) => !m.svgPath).map((m) => m.key),
      labels: [...picked.values()].reduce((n, m) => n + (m.labels?.length ?? 0), 0),
    },
    null,
    1,
  ),
)
